import ai_error_handler.error_explainer
n=6
for i in n:
    print(i)